#!/usr/bin/env bash
#
# cockpit.sh: regenerate docs/epics/STATUS.md from the epic/story files.
#
# Source of truth is the files themselves:
#   - Each epic is a folder  EPIC-NN-<slug>/  containing  epic.md
#   - Each story is a file    EPIC-NN-<slug>/STORY-NN-<slug>.md
#   - Tasks are GitHub-style checkboxes inside a story:  "- [ ]" / "- [x]"
#   - Status (todo|in-progress|done|blocked|halted) lives in YAML frontmatter.
#
# Percentages are computed from task checkboxes; status labels are read
# verbatim from frontmatter. Run this after editing any epic/story.
#
# Usage:  ./docs/epics/cockpit.sh        # writes STATUS.md
#         ./docs/epics/cockpit.sh --stdout  # print to stdout instead

set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
OUT="$HERE/STATUS.md"
WIDTH=10

# field <file> <key> -> first frontmatter value for key (trimmed), or ""
field() {
  sed -n '/^---$/,/^---$/p' "$1" \
    | grep -m1 -E "^$2:" \
    | sed -E "s/^$2:[[:space:]]*//; s/[[:space:]]*$//" || true
}

# count_open / count_done <file>
count_open() { grep -cE '^[[:space:]]*- \[ \]'  "$1" 2>/dev/null || true; }
count_done() { grep -ciE '^[[:space:]]*- \[x\]' "$1" 2>/dev/null || true; }

# bar <done> <total> -> "█████░░░░░"
bar() {
  local d=$1 t=$2 f=0 i out=""
  (( t > 0 )) && f=$(( d * WIDTH / t ))
  for ((i = 0; i < f; i++)); do out+="█"; done
  for ((i = f; i < WIDTH; i++)); do out+="░"; done
  printf '%s' "$out"
}

# pct <done> <total>
pct() { (( $2 > 0 )) && echo $(( $1 * 100 / $2 )) || echo 0; }

grand_done=0
grand_total=0
grand_mvp_done=0
grand_mvp_total=0
body=""
prev_iter=""

shopt -s nullglob
# Walk the epics grouped by iteration, then by number: an epic added to an
# earlier iteration later on gets a higher number, and number order alone
# would split that iteration's section in two.
sorted_epic_dirs=()
while IFS=$'\t' read -r _iter _dir; do
  sorted_epic_dirs+=("$_dir")
done < <(
  for d in "$HERE"/EPIC-*/; do
    [[ -f "$d/epic.md" ]] || continue
    it="$(field "$d/epic.md" iteration)"
    it="${it%%[^0-9]*}"
    printf '%s\t%s\n' "${it:-999}" "$d"
  done | sort -t$'\t' -k1,1n -k2,2
)

for epic_dir in "${sorted_epic_dirs[@]}"; do
  epic_md="$epic_dir/epic.md"
  [[ -f "$epic_md" ]] || continue

  epic_id="$(field "$epic_md" id)"
  epic_title="$(field "$epic_md" title)"
  epic_status="$(field "$epic_md" status)"
  [[ -n "$epic_status" ]] || epic_status="todo"

  # Group epics under their iteration (see ITERATIONS.md for the narrative).
  epic_iter="$(field "$epic_md" iteration)"
  [[ -n "$epic_iter" ]] || epic_iter="(unassigned)"
  if [[ "$epic_iter" != "$prev_iter" ]]; then
    body+="$(printf '## Iteration %s\n' "$epic_iter")"$'\n\n'
    prev_iter="$epic_iter"
  fi

  epic_done=0
  epic_total=0
  stories=""

  for story_md in "$epic_dir"STORY-*.md; do
    s_id="$(field "$story_md" id)"
    s_title="$(field "$story_md" title)"
    s_status="$(field "$story_md" status)"
    [[ -n "$s_status" ]] || s_status="todo"
    o="$(count_open "$story_md")"; o=${o:-0}
    d="$(count_done "$story_md")"; d=${d:-0}
    t=$(( o + d ))
    epic_done=$(( epic_done + d ))
    epic_total=$(( epic_total + t ))
    mvp_mark=""
    if [[ -n "$(field "$story_md" milestone)" ]]; then
      mvp_mark=" · MVP"
      grand_mvp_done=$(( grand_mvp_done + d ))
      grand_mvp_total=$(( grand_mvp_total + t ))
    fi
    stories+="$(printf -- '- **%s** %s [%s, %s/%s]%s\n' "$s_id" "$s_title" "$s_status" "$d" "$t" "$mvp_mark")"$'\n'
  done

  grand_done=$(( grand_done + epic_done ))
  grand_total=$(( grand_total + epic_total ))

  body+="$(printf '### %s · %s\n`%s` %s %s%% (%s/%s)\n\n%s\n' \
    "$epic_id" "$epic_title" "$epic_status" \
    "$(bar "$epic_done" "$epic_total")" "$(pct "$epic_done" "$epic_total")" \
    "$epic_done" "$epic_total" "$stories")"$'\n\n'
done
shopt -u nullglob

mvp_line=""
if (( grand_mvp_total > 0 )); then
  mvp_line="$(printf '\n**MVP:** %s %s%% (%s/%s tasks)' \
    "$(bar "$grand_mvp_done" "$grand_mvp_total")" "$(pct "$grand_mvp_done" "$grand_mvp_total")" \
    "$grand_mvp_done" "$grand_mvp_total")"
fi
header="$(printf '# SidecarTridge Rescue ROM Switcher Cockpit\n\n_Generated by `docs/epics/cockpit.sh`. Do not edit by hand; run the script after changing any epic/story._\n\n**Overall:** %s %s%% (%s/%s tasks)%s\n' \
  "$(bar "$grand_done" "$grand_total")" "$(pct "$grand_done" "$grand_total")" \
  "$grand_done" "$grand_total" "$mvp_line")"

result="$header"$'\n\n'"$body"

if [[ "${1:-}" == "--stdout" ]]; then
  printf '%s\n' "$result"
else
  printf '%s\n' "$result" > "$OUT"
  echo "Wrote $OUT  ($grand_done/$grand_total tasks, $(pct "$grand_done" "$grand_total")%)"
fi
