/**
 * File: src/st/mem.h
 * Author: Diego Parrilla Santamaría
 * Date: 2026-03-11
 * Copyright: 2024-26 - GOODDATA LABS SL
 * Description: Atari ST memory layout constants.
 */

#pragma once

#ifndef ROM_BASE_ADDR_UL
#error "ROM_BASE_ADDR_UL must be defined before including mem.h"
#endif

#define ST_ROM_ST_SIZE_BYTES 0x00030000UL
#define ST_ROM_STE_SIZE_BYTES 0x00040000UL
#define ST_ROM_CRC_FIELD_SIZE_BYTES 4UL

#if (ROM_BASE_ADDR_UL == 0x00FC0000UL)
#define ST_ROM_IMAGE_SIZE_BYTES ST_ROM_ST_SIZE_BYTES
#elif (ROM_BASE_ADDR_UL == 0x00E00000UL)
#define ST_ROM_IMAGE_SIZE_BYTES ST_ROM_STE_SIZE_BYTES
#else
#error "Unsupported ST/STE ROM base address"
#endif

#define ST_ROM_CRC_FIELD_OFFSET_BYTES \
  (ST_ROM_IMAGE_SIZE_BYTES - ST_ROM_CRC_FIELD_SIZE_BYTES)

#define ST_RAM_TOP_ADDR_UL 0x00080000
#define ST_STACK_TOP_ADDR_UL (ST_RAM_TOP_ADDR_UL - 32768)
#define ST_RAM_VARS_BASE_ADDR_UL (ST_STACK_TOP_ADDR_UL - (128 * 1024))
#define ST_RAM_VARS_SIZE_BYTES (124 * 1024)
#define ST_RAM_VARS_RESERVED_BYTES 8
#define ST_RAM_VARS_ALLOC_BASE_ADDR_UL \
  (ST_RAM_VARS_BASE_ADDR_UL + ST_RAM_VARS_RESERVED_BYTES)
#define ST_RAM_VARS_ALLOC_SIZE_BYTES \
  (ST_RAM_VARS_SIZE_BYTES - ST_RAM_VARS_RESERVED_BYTES)
#define ST_RAM_EXEC_BASE_ADDR_UL ST_RAM_VARS_ALLOC_BASE_ADDR_UL

#define ST_SCREEN_BASE_ADDR_UL ST_STACK_TOP_ADDR_UL
#define ST_SCREEN_SIZE_BYTES 32000

#if !defined(__ASSEMBLER__)

/* Compile-time layout guards. */
enum {
  ST_LAYOUT_VARS_END = ST_RAM_VARS_BASE_ADDR_UL + ST_RAM_VARS_SIZE_BYTES,
  ST_LAYOUT_SCREEN_END = ST_SCREEN_BASE_ADDR_UL + ST_SCREEN_SIZE_BYTES,
  ST_LAYOUT_CHECK_RESERVED_VARS =
      1 / ((ST_RAM_VARS_RESERVED_BYTES < ST_RAM_VARS_SIZE_BYTES) ? 1 : 0),
  ST_LAYOUT_CHECK_EXEC_IN_VARS =
      1 / (((ST_RAM_EXEC_BASE_ADDR_UL >= ST_RAM_VARS_ALLOC_BASE_ADDR_UL) &&
            (ST_RAM_EXEC_BASE_ADDR_UL < ST_LAYOUT_VARS_END))
               ? 1
               : 0),
  ST_LAYOUT_CHECK_SCREEN_TOP =
      1 / ((ST_LAYOUT_SCREEN_END <= ST_RAM_TOP_ADDR_UL) ? 1 : 0),
  ST_LAYOUT_CHECK_SCREEN_VARS_NON_OVERLAP =
      1 / (((ST_LAYOUT_VARS_END <= ST_SCREEN_BASE_ADDR_UL) ||
            (ST_LAYOUT_SCREEN_END <= ST_RAM_VARS_BASE_ADDR_UL))
               ? 1
               : 0),
  ST_LAYOUT_CHECK_VARS_TOP =
      1 / ((ST_LAYOUT_VARS_END <= ST_RAM_TOP_ADDR_UL) ? 1 : 0)
};

#define ST_SCREEN_BASE_ADDR ((unsigned long)ST_SCREEN_BASE_ADDR_UL)
#define ST_RAM_VARS_BASE_ADDR ((unsigned long)ST_RAM_VARS_BASE_ADDR_UL)

#endif
