#pragma once

#include "screen.h"

/*
 * Text/terminal abstraction layer.
 * TERM_* names decouple the text renderer from ST-specific identifiers.
 */
#define TERM_RAM_TOP_ADDR_UL ST_RAM_TOP_ADDR_UL
#define TERM_STACK_TOP_ADDR_UL ST_STACK_TOP_ADDR_UL
#define TERM_SCREEN_BASE_ADDR_UL ST_SCREEN_BASE_ADDR_UL
#define TERM_SCREEN_SIZE_BYTES ST_SCREEN_SIZE_BYTES
#define TERM_RAM_VARS_BASE_ADDR_UL ST_RAM_VARS_BASE_ADDR_UL
#define TERM_RAM_VARS_SIZE_BYTES ST_RAM_VARS_SIZE_BYTES

#define TERM_STACK_TOP_ADDR ST_STACK_TOP_ADDR
#define TERM_SCREEN_BASE_ADDR ST_SCREEN_BASE_ADDR
#define TERM_RAM_VARS_BASE_ADDR ST_RAM_VARS_BASE_ADDR

#define TERM_VIDEO_BASE ST_VIDEO_BASE

#define TERM_CURSOR_COL ST_CURSOR_COL
#define TERM_CURSOR_ROW ST_CURSOR_ROW
#define TERM_TEXT_COLOR ST_TEXT_COLOR
#define TERM_VIDEO_MODE ST_VIDEO_MODE
#define TERM_VIDEO_MODE_VALID ST_VIDEO_MODE_VALID
