/**
 * File: src/amiga/mem.h
 * Author: Diego Parrilla Santamaría
 * Date: 2026-03-11
 * Copyright: 2024-26 - GOODDATA LABS SL
 * Description: Amiga memory layout constants.
 */

#pragma once

#ifndef ROM_BASE_ADDR_UL
#error "ROM_BASE_ADDR_UL must be defined before including mem.h"
#endif

#define AMIGA_ROM_SIZE_BYTES 0x00080000
#define AMIGA_ROM_KICKETY_OFFSET_BYTES (AMIGA_ROM_SIZE_BYTES / 2)
#define AMIGA_ROM_FOOTER_SIZE_BYTES 24
#define AMIGA_ROM_FOOTER_OFFSET_BYTES \
  (AMIGA_ROM_SIZE_BYTES - AMIGA_ROM_FOOTER_SIZE_BYTES)

#define AMIGA_CHIP_RAM_TOP_ADDR_UL 0x00080000

#define AMIGA_STACK_SIZE_BYTES 0x00008000
#define AMIGA_STACK_TOP_ADDR_UL AMIGA_CHIP_RAM_TOP_ADDR_UL
#define AMIGA_STACK_BOTTOM_ADDR_UL \
  (AMIGA_STACK_TOP_ADDR_UL - AMIGA_STACK_SIZE_BYTES)

#define AMIGA_SCREEN_PLANE_COUNT 2
#define AMIGA_SCREEN_REGION_SIZE_BYTES 0x0000A000
#define AMIGA_SCREEN_BASE_ADDR_UL \
  (AMIGA_STACK_BOTTOM_ADDR_UL - AMIGA_SCREEN_REGION_SIZE_BYTES)
#define AMIGA_SCREEN_ROW_BYTES 80
#define AMIGA_SCREEN_HEIGHT_LINES 256
#define AMIGA_SCREEN_SIZE_BYTES 0x00005000
#define AMIGA_SCREEN_PLANE_SIZE_BYTES AMIGA_SCREEN_SIZE_BYTES
#define AMIGA_TEXT_ROW_BYTES 0x00000280

#define AMIGA_RAM_VARS_SIZE_BYTES 0x00030000
#define AMIGA_RAM_VARS_RESERVED_BYTES 8
#define AMIGA_RAM_VARS_BASE_ADDR_UL \
  (AMIGA_SCREEN_BASE_ADDR_UL - AMIGA_RAM_VARS_SIZE_BYTES)
#define AMIGA_RAM_VARS_ALLOC_BASE_ADDR_UL \
  (AMIGA_RAM_VARS_BASE_ADDR_UL + AMIGA_RAM_VARS_RESERVED_BYTES)
#define AMIGA_RAM_VARS_ALLOC_SIZE_BYTES \
  (AMIGA_RAM_VARS_SIZE_BYTES - AMIGA_RAM_VARS_RESERVED_BYTES)
#define AMIGA_RAM_EXEC_BASE_ADDR_UL AMIGA_RAM_VARS_ALLOC_BASE_ADDR_UL

#if !defined(__ASSEMBLER__)

enum {
  AMIGA_LAYOUT_VARS_END =
      AMIGA_RAM_VARS_BASE_ADDR_UL + AMIGA_RAM_VARS_SIZE_BYTES,
  AMIGA_LAYOUT_SCREEN_END =
      AMIGA_SCREEN_BASE_ADDR_UL + AMIGA_SCREEN_REGION_SIZE_BYTES,
  AMIGA_LAYOUT_CHECK_RESERVED_VARS =
      1 / ((AMIGA_RAM_VARS_RESERVED_BYTES < AMIGA_RAM_VARS_SIZE_BYTES) ? 1 : 0),
  AMIGA_LAYOUT_CHECK_EXEC_IN_VARS =
      1 / (((AMIGA_RAM_EXEC_BASE_ADDR_UL >= AMIGA_RAM_VARS_ALLOC_BASE_ADDR_UL) &&
            (AMIGA_RAM_EXEC_BASE_ADDR_UL < AMIGA_LAYOUT_VARS_END))
               ? 1
               : 0),
  AMIGA_LAYOUT_CHECK_VARS_SCREEN_NON_OVERLAP =
      1 / ((AMIGA_LAYOUT_VARS_END <= AMIGA_SCREEN_BASE_ADDR_UL) ? 1 : 0),
  AMIGA_LAYOUT_CHECK_SCREEN_STACK_NON_OVERLAP =
      1 / ((AMIGA_LAYOUT_SCREEN_END <= AMIGA_STACK_BOTTOM_ADDR_UL) ? 1 : 0),
  AMIGA_LAYOUT_CHECK_STACK_CHIPRAM_TOP =
      1 / ((AMIGA_STACK_TOP_ADDR_UL <= AMIGA_CHIP_RAM_TOP_ADDR_UL) ? 1 : 0),
  AMIGA_LAYOUT_CHECK_SCREEN_REGION =
      1 / (((AMIGA_SCREEN_PLANE_SIZE_BYTES * AMIGA_SCREEN_PLANE_COUNT) <=
            AMIGA_SCREEN_REGION_SIZE_BYTES)
               ? 1
               : 0)
};

#define AMIGA_SCREEN_BASE_ADDR ((unsigned long)AMIGA_SCREEN_BASE_ADDR_UL)
#define AMIGA_RAM_VARS_BASE_ADDR ((unsigned long)AMIGA_RAM_VARS_BASE_ADDR_UL)

#endif
